### ISSUE TITLE
receved error when trying to install the OJT plug-in on Totara 10

### ISSUE THREAD

**Issue by mbrown-OU** [catalyst/totara-mod-ojt#21]
I was very excited to see your OJT plug-in. It is exactly what we need for a project we support, but when we tried to install it, received as error message (see image below). 
![Screenshot from 2019-11-14 16-43-07](https://user-images.githubusercontent.com/57802707/68950580-09d02400-0782-11ea-9f14-049f73d51b40.png)

Can you please let me know if there is a version of this plug-in that work with Totara 10 and eventually 12? 

Sincerely, 
Malinda Brown

**Comment by danmarsden** [comment]
Hi there,

Support for older branches is available using the branches in github here:
https://github.com/catalyst/totara-mod-ojt/branches

You should be able to see one that looks like a Totara 10 branch.

but... T 10 is pretty old and you should really be spending time on upgrading rather than adding extra plugins to your site - once you've upgraded, then think about adding plugins like OJT.
